// Code generated by Kitex v0.5.2. DO NOT EDIT.

package transferservice

import (
	"context"
	transfrom "github.com/aesoper101/kitextest/kitex_gen/transfrom"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	TransIn(ctx context.Context, Req *transfrom.TransferRequest, callOptions ...callopt.Option) (r *transfrom.Message, err error)
	TransOut(ctx context.Context, Req *transfrom.TransferRequest, callOptions ...callopt.Option) (r *transfrom.Message, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTransferServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTransferServiceClient struct {
	*kClient
}

func (p *kTransferServiceClient) TransIn(ctx context.Context, Req *transfrom.TransferRequest, callOptions ...callopt.Option) (r *transfrom.Message, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.TransIn(ctx, Req)
}

func (p *kTransferServiceClient) TransOut(ctx context.Context, Req *transfrom.TransferRequest, callOptions ...callopt.Option) (r *transfrom.Message, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.TransOut(ctx, Req)
}
